// <auto-generated />
using System;
using GamesRankingSteamAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamesRankingSteamAPI.Migrations
{
    [DbContext(typeof(gamesrankdbContext))]
    [Migration("20201208220048_GamesRankingDBv1.1")]
    partial class GamesRankingDBv11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GamesRankingSteamAPI.Models.Games", b =>
                {
                    b.Property<long?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Pegi")
                        .HasColumnName("PEGI")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("varchar(1000)")
                        .HasComment("opis - opis gry video (kopiuj wklej z strony internetowej zawierającej informacje o grze)")
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("URL")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("GameId")
                        .HasName("PRIMARY");

                    b.HasIndex("GenreId")
                        .HasName("fk_Games_Genres_idx");

                    b.ToTable("games");
                });

            modelBuilder.Entity("GamesRankingSteamAPI.Models.Genres", b =>
                {
                    b.Property<long?>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("GenreId")
                        .HasName("PRIMARY");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("GamesRankingSteamAPI.Models.Top10populargames", b =>
                {
                    b.Property<long?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasComment("nazwa_gra - nazwa gry video")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("date");

                    b.HasKey("GameId")
                        .HasName("PRIMARY");

                    b.ToTable("top10populargames");
                });

            modelBuilder.Entity("GamesRankingSteamAPI.Models.Top15interestinggames", b =>
                {
                    b.Property<long?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FirstReleaseDate")
                        .HasColumnType("date");

                    b.Property<long?>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .HasColumnName("URL")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("GameId")
                        .HasName("PRIMARY");

                    b.HasIndex("GenreId")
                        .HasName("fk_Top15InterestingGames_Genres1_idx");

                    b.ToTable("top15interestinggames");
                });

            modelBuilder.Entity("GamesRankingSteamAPI.Models.Games", b =>
                {
                    b.HasOne("GamesRankingSteamAPI.Models.Genres", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("fk_Games_Genres");
                });

            modelBuilder.Entity("GamesRankingSteamAPI.Models.Top15interestinggames", b =>
                {
                    b.HasOne("GamesRankingSteamAPI.Models.Genres", "Genre")
                        .WithMany("Top15interestinggames")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("fk_Top15InterestingGames_Genres1");
                });
#pragma warning restore 612, 618
        }
    }
}
